# -*- coding: utf-8 -*-
"""
/***************************************************************************
 IGprojekt2
                                 A QGIS plugin
 Ta wtyczka liczy różnice wysokości i pola powierzchni
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-06-05
        copyright            : (C) 2024 by Dawid Paska, Mateusz Kołodziejczak
        email                : dawid.paska.stud@pw.edu.pl, mateusz.kolodziejczak.stud@pw.edu.pl
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load IGprojekt2 class from file IGprojekt2.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .IG_projekt2_Loader import IGprojekt2
    return IGprojekt2(iface)
